name: Create js artifact
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - run: yarn install --frozen-lockfile
      - run: yarn tsc
      - name: Archive js output
        uses: actions/upload-artifact@v3
        with:
          name: js
          path: |
            out/*
            package.json
      - name: release
        uses: actions/create-release@v1
        id: make_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.make_release.outputs.upload_url }}
          asset_path: ./out
          asset_name: main.js
